---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.5-jdk-8-slim

inputs:
  - name: dp-dataset-exporter-xlsx

outputs:
  - name: build

run:
  path: dp-dataset-exporter-xlsx/ci/scripts/build.sh