---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-java

inputs:
  - name: dp-dataset-exporter-xlsx

outputs:
  - name: build

run:
  path: dp-dataset-exporter-xlsx/ci/scripts/build.sh